### PR TITLE
Fix some scrutinizer issues

### PR DESCRIPTION
**Pull request by manavo**
Refs #14

### CODE REVIEW

**Comment by manavo** [comment]
Fixed as many as I could work out @niclasleonbock, not sure how to solve the calls on `app()` that Scrutinizer is unhappy with!

**Comment by niclasleonbock** [comment]
Hi,
thank you so far!

Regarding your question: You could try to use the facades or dependencies directly instead of calling `app()` to resolve them. I'm not sure if these are the calls that Scrutinizer is complaining about, though.

I'll take a deeper look at it later today. Maybe I can sort out some of them.

**Comment by niclasleonbock** [comment]
So, for `app()->environment()` we could also use the `Environment` facade.

The other issues are not related to `app()` calls as I can see.

**Comment by niclasleonbock** [comment]
Hi again,
I'll merge the PR now. If you want to fix some other issues, feel free to open a new pull request.

Thanks again for your contribution.

**Comment by manavo** [comment]
Hey, sorry for the late reply!

I guess you could change it to the Environment facade, but something feels a little wrong to adjust your code just to satisfy Scrutinizer, when using the `app()->` calls is what Laravel itself encourages (if I'm not mistaken). Hard to find the right balance!

**Comment by manavo** [comment]
Thanks for merging though, I'll have a look and see if I can find a way of satisfying it, or what the root cause of it is where it fails to find the necessary signatures.

**Comment by niclasleonbock** [comment]
Hi,
you're absolutely right. I wonder how other laravel-based projects are handling scrutinizer. I don't think that the hacktoberfest checker is the only laravel app using it.

Maybe we can find some other project where scrutinizer is also used so that we can take a look at their config.

**Pull request merged**
